<?php include 'header.php'; ?>

        <div class="container">
          <div class="row">
            <div class="span12 faqpolicyterm">
              <h3>Privacy Policy</h3>
              <p>This Privacy Policy was last modified on Jan 9, 2012 and was first published and made effective on Jan 9, 2012.</p><br>
              <p>ScrapOn, Inc. ("ScrapOn," "we," or "us") knows that you care how information about you is used and shared. This Privacy Policy explains what information of yours will be collected by ScrapOn when you use the ScrapOn Service, how the information will be used, and how you can control the collection, correction and/or deletion of information. We will not use or share your information with anyone except as described in this Privacy Policy. This Privacy Policy does not apply to information we collect by other means (including offline) or from other sources. Capitalized terms that are not defined in this Privacy Policy have the meaning given them in our Terms of Use.</p><br>
              <p><strong>Information We Collect</strong></p><br>
              <p><span class="blakish">User-Provided Information:</span> You provide us information about yourself, such as your name, e-mail address, and other personal information if you register for a User account with the Service (including by "following," "liking," adding the ScrapOn application, linking your account to the ScrapOn service, etc., on a third party website or network). If you correspond with us by email, we may retain the content of your email messages, your email address and our responses. We may also retain any messages you send through the Service. You may provide us information in User Content you post to the Service.</p><br>
              <p><span class="blakish">Cookies Information:</span> When you visit the Service, we may send one or more cookies - a small text file containing a string of alphanumeric characters - to your computer that uniquely identifies your browser and lets ScrapOn help you log in faster and enhance your navigation through the site. A cookie may also convey information about how you browse the Service to us. A cookie does not collect personal information about you. A persistent cookie remains on your hard drive after you close your browser. Persistent cookies may be used by your browser on subsequent visits to the site. Persistent cookies can be removed by following your web browser's directions. A session cookie is temporary and disappears after you close your browser. You can reset your web browser to refuse all cookies or to indicate when a cookie is being sent. However, some features of the Service may not function properly if the ability to accept cookies is disabled.</p><br>
              <p><span class="blakish">Cookies Information:</span> When you visit the Service, we may send one or more cookies - a small text file containing a string of alphanumeric characters - to your computer that uniquely identifies your browser and lets ScrapOn help you log in faster and enhance your navigation through the site. A cookie may also convey information about how you browse the Service to us. A cookie does not collect personal information about you. A persistent cookie remains on your hard drive after you close your browser. Persistent cookies may be used by your browser on subsequent visits to the site. Persistent cookies can be removed by following your web browser's directions. A session cookie is temporary and disappears after you close your browser. You can reset your web browser to refuse all cookies or to indicate when a cookie is being sent. However, some features of the Service may not function properly if the ability to accept cookies is disabled.</p><br>
              <p><span class="blakish">Log File Information:</span> Log file information is automatically reported by your browser each time you access a web page. When you use the Service, our servers automatically record certain log file information. These server logs may include information such as your web request, Internet Protocol ("IP") address, browser type, referring / exit pages and URLs, number of clicks and how you interact with links on the Service, domain names, landing pages, pages viewed, and other such information.</p><br>
              <p>Log file information is automatically reported by your browser each time you access a web page. When you use the Service, our servers automatically record certain log file information. These server logs may include information such as your web request, Internet Protocol ("IP") address, browser type, referring / exit pages and URLs, number of clicks and how you interact with links on the Service, domain names, landing pages, pages viewed, and other such information.</p><br>
              <p>Log file information is automatically reported by your browser each time you access a web page. When you use the Service, our servers automatically record certain log file information. These server logs may include information such as your web request, Internet Protocol ("IP") address, browser type, referring / exit pages and URLs, number of clicks and how you interact with links on the Service, domain names, landing pages, pages viewed, and other such information.</p><br>
              <p><span class="blakish">ETC ETC ETC ALL THE LEGAL PRIVACY STUFF</span></p><br><br><br>
              
            </div>
          </div>
        </div>        
  		
<?php include 'footer.php'; ?>   